name: Action test
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-html:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test Asciidoctor run
      uses: ./
      with:
        files: 'test/*.adoc test/**/*.adoc'
      env:
        TEST_COMMAND: |-
          asciidoctor -R . -D /github/workspace/asciidoc-out -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json -a source-highlighter@=rouge test/index.adoc test/index.adoc test/subdir/subdir.adoc test/subdir/subsubdir/index.adoc test/subdir/subsubdir/subsubdir.adoc test/subdir/subsubdir/vamoose.adoc test/subdir2/subdir2.adoc
        TEST_OUTPUT: |-
          ::set-output name=asciidoctor-artifacts::asciidoc-out
  test-html-args:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test Asciidoctor run with args
      uses: ./
      with:
        files: 'test/*.adoc test/**/*.adoc'
        asciidoctor-args: "-a revdate=`date +%Y-%m-%d` --failure-level=ERROR"
      env:
        DATE: '+%Y-%m-%d'
        TEST_COMMAND: |-
          asciidoctor -R . -D /github/workspace/asciidoc-out -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json -a source-highlighter@=rouge -a revdate=`date +%Y-%m-%d` --failure-level=ERROR test/index.adoc test/index.adoc test/subdir/subdir.adoc test/subdir/subsubdir/index.adoc test/subdir/subsubdir/subsubdir.adoc test/subdir/subsubdir/vamoose.adoc test/subdir2/subdir2.adoc
        TEST_OUTPUT: |-
          ::set-output name=asciidoctor-artifacts::asciidoc-out
  test-pdf:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test Asciidoctor PDF run
      uses: ./
      with:
        files: 'test/*.adoc test/**/*.adoc'
        format: 'pdf'
      env:
        TEST_COMMAND: |-
          asciidoctor-pdf -R . -D /github/workspace/asciidoc-out -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json -a source-highlighter@=rouge test/index.adoc test/index.adoc test/subdir/subdir.adoc test/subdir/subsubdir/index.adoc test/subdir/subsubdir/subsubdir.adoc test/subdir/subsubdir/vamoose.adoc test/subdir2/subdir2.adoc
        TEST_OUTPUT: |-
          ::set-output name=asciidoctor-artifacts::asciidoc-out
  test-pdf-args:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test Asciidoctor PDF run with args
      uses: ./
      with:
        files: 'test/*.adoc test/**/*.adoc'
        format: pdf
        asciidoctor-args: '-a revdate=`date +%Y-%m-%d` --failure-level=ERROR'
      env:
        TEST_COMMAND: |-
          asciidoctor-pdf -R . -D /github/workspace/asciidoc-out -r asciidoctor-diagram -a mermaid-puppeteer-config=/mermaid/puppeteer-config.json -a source-highlighter@=rouge -a revdate=`date +%Y-%m-%d` --failure-level=ERROR test/index.adoc test/index.adoc test/subdir/subdir.adoc test/subdir/subsubdir/index.adoc test/subdir/subsubdir/subsubdir.adoc test/subdir/subsubdir/vamoose.adoc test/subdir2/subdir2.adoc
        TEST_OUTPUT: |-
          ::set-output name=asciidoctor-artifacts::asciidoc-out
